name: Deploy to Replicate

on:
 push:
   branches: [main]
 workflow_dispatch:

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3
     with:
       submodules: "recursive"

   - name: Install Cog
     run: |
       sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
       sudo chmod +x /usr/local/bin/cog

   - name: cog login
     run: |
       echo "cba8f10f-5d7e-4d2d-8d14-55e08de89f74" | cog login --token-stdin

   - name: Push to Replicate
     run: |
       cog push r8.im/imazdarx7/flux-lora-trainer
