name: Deploy to Replicate

on:
 push:
   branches: [main]
 workflow_dispatch:

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3
     with:
       submodules: "recursive"

   - name: Install Cog
     run: |
       sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
       sudo chmod +x /usr/local/bin/cog

   - name: cog login
     run: |
       echo ${{ secrets.REPLICATE_API_TOKEN }} | cog login --token-stdin

   - name: Push to Replicate
     env:
       HF_TOKEN: ${{ secrets.HF_TOKEN }}
       REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
     run: |
       cog push r8.im/imazdarx7/flux-lora-trainer
